version: "3.7"

services:
  app:
    build: .
    container_name: nutri-back
    depends_on:
      - db
    ports:
      - ${PORT}:${PORT}
    volumes:
      - .:/usr/app
    command: sh -c "npx prisma migrate dev && npm run start"
  db:
    container_name: nutri-db
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./postgres-data:/var/lib/postgressql/data
      - ./data/dump.sql:/docker-entrypoint-initdb.d/dump.sql
